----------------------------------------------------------------
Thu May 23 11:29:47 NZST 2024:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.14.2.0 - (1828579): instance a816c00e-018f-a2a3-b0fc-00000eb8ebe0 
on database directory C:\Users\harsh\Downloads\P09_22164966_22174809\AUT_ECMS_QA_FORUM_\AUT_ECMS_QA_FORUM\AUT_ECMS_QA_FORUM\forumDB with class loader jdk.internal.loader.ClassLoaders$AppClassLoader@659e0bfd 
Loaded from file:/C:/Users/harsh/Downloads/P09_22164966_22174809/AUT_ECMS_QA_FORUM_/AUT_ECMS_QA_FORUM/AUT_ECMS_QA_FORUM/lib/derby.jar
java.vendor=Eclipse Adoptium
java.runtime.version=17.0.8.1+1
user.dir=C:\Users\harsh\Downloads\P09_22164966_22174809\AUT_ECMS_QA_FORUM_\AUT_ECMS_QA_FORUM\AUT_ECMS_QA_FORUM
os.name=Windows 11
os.arch=amd64
os.version=10.0
derby.system.home=null
Database Class Loader started - derby.database.classpath=''
Thu May 23 11:33:07 NZST 2024 Thread[Thread-0,5,main] (XID = 2596), (SESSIONID = 2), (DATABASE = forumDB), (DRDAID = null), Cleanup action starting
java.sql.SQLNonTransientConnectionException: Connection authentication failure occurred.  Reason: Invalid authentication..
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:252)
	at aut_ecms_qa_forum.DerbyDatabaseManager.shutdownDatabase(DerbyDatabaseManager.java:28)
	at aut_ecms_qa_forum.LoginGUI.lambda$main$0(LoginGUI.java:79)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: ERROR 08004: Connection authentication failure occurred.  Reason: Invalid authentication..
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 19 more
============= begin nested exception, level (1) ===========
ERROR 08004: Connection authentication failure occurred.  Reason: Invalid authentication..
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:252)
	at aut_ecms_qa_forum.DerbyDatabaseManager.shutdownDatabase(DerbyDatabaseManager.java:28)
	at aut_ecms_qa_forum.LoginGUI.lambda$main$0(LoginGUI.java:79)
	at java.base/java.lang.Thread.run(Thread.java:833)
============= end nested exception, level (1) ===========
Cleanup action completed
